name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
    paths-ignore:
      - '.dockerignore'
      - '.gcloudignore'
      - 'app.yaml'
      - '**/readme_media/**' 
      - 'README.MD'
      - '**/venv/**'

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Add remote
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git remote add space https://Mohammed-Altaf:$HF_TOKEN@huggingface.co/spaces/Mohammed-Altaf/Farmwise
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git lfs install
          git lfs fetch
          git lfs push https://$HF_TOKEN@huggingface.co/spaces/Mohammed-Altaf/Farmwise main